### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by JPDSousa** [paul-krohn/python_nexus#4]
Hi,

First of all, congrats on the project :) This seems a very cool, useful and simple idea!

I was looking at your README and I was wondering: does it support authentication? I mean, what if the nexus I'm trying to access has, for instance, LDAP authentication?

**Comment by paul-krohn** [comment]
At the time that I wrote this, only HTTP Basic Auth was supported/provided by Nexus; you can pass in the user & password as keyword arguments to the `Nexus()` constructor. If you would like to add more auth methods, then be my guest!

**Comment by JPDSousa** [comment]
Well, didn't see that at first, but it seems to be exactly what I want!

I'll give it a try, thanks 👍
